name = "flora-bar-c299"
main = "api/index.js"
compatibility_date = "2024-11-11"

[vars]
BOT_TOKEN = "7228651385:AAHvVY9oZAzqoZp2aeProh1i16riopePySM"
BOT_USERNAME = "Ajereactionbot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "0"
RESTRICTED_CHATS = "1234,5678"

[build]
command = "npm run build"
cwd = "build_cwd"
watch_dir = "build_watch_dir"

